### ISSUE TITLE
提出データの取得・更新を自動化するのはいかがでしょうか?

### ISSUE THREAD

**Issue by KATO-Hiro** [Inazuma110/atcoder_language_visualizer#2]
連続の投稿となり、失礼いたします。

#1 に関連した内容です。

もし可能であれば、ご対応いただけると幸いです。

## WHY

- 定型作業であり、更新忘れを防ぐため

## WHAT

- GitHub ActionsやCircle CIなどを利用して、データ更新作業およびデプロイを自動化するのはいかがでしょうか?以下の内容は、GitHub Actionsを利用したときに想定される手順の一例です。
  1. GitHub Actionsを利用するための設定ファイル(.yml)を用意する
  2. 一連の処理を実行する日時、トリガーとなる操作を指定する
  3. 設定ファイル内で、Python（やNode.js）の実行環境を構築するとともに、依存パッケージをインストールする
  4. main.pyを実行して、提出に関するデータを.jsonに変換する
  5. 4.で生成したファイルをレポジトリに追加し、コミットする
  6. （必要に応じて）Vueのプロジェクトをビルド&デプロイする

**Comment by Inazuma110** [comment]
ありがとうございます．

自動化はやりたいところなのですが，GitHub Actionsで使えるストレージが，フリープランだと500MBのようです．
Dataset が1GBを超えるので，どうしてもそれ以上のストレージが必要です．
お金で解決できるのですが，できればお金をかけたくない，というのが本音です…

なにか，無料で自動化できる良い案はありませんか？

**Comment by KATO-Hiro** [comment]
早速の返信をいただき、ありがとうございます。

以下の方法はいかがでしょうか?

## ご自身のPCを指定した時間に起動し、データの更新処理をまとめたスクリプトを実行する

かなり原始的かもしれませんが、手動で行なってきた作業をほぼそのままPCに任せる方法です。

- 提出データの取得〜レポジトリにマージするまでの操作
  - シェルスクリプトなどでスクリプト化する
  - GitHubに関する操作は、GitHub CLIで実行できそうです（既にご存知でしたら、ご容赦ください）

  See:
  https://github.com/cli/cli
  https://qiita.com/ryo2132/items/2a29dd7b1627af064d7b

- スクリプトの定期実行
  - OSで用意されているPCの自動起動・終了機能と定期実行ツール（cronやタスクスケジューラなど）を併用する

**Comment by KATO-Hiro** [comment]
勘違いしていた部分がありましたので、該当箇所を削除しました。

**Comment by Inazuma110** [comment]
ありがとうございます．
cronを用いて自動化を行ってみようと思います．

**Comment by Inazuma110** [comment]
手元にデスクトップが無いので，研究室のサーバーで自動更新するようにしました．
私の卒業まであと2年の予定なので(それ以降どうするか決まってないですが)，ひとまず2年間は大丈夫なはずです．

**Comment by KATO-Hiro** [comment]
ご対応いただき、ありがとうございます。

今後とも、よろしくお願いいたします。
